services:
  peggo:
    image:  public.ecr.aws/l9h3g6c6/peggo:v1.15.2
    container_name: peggo_sidecar
    working_dir: /opt/peggo
    restart: unless-stopped
    volumes:
      - ./peggo:/opt/peggo
      - ./injective:/opt/injectived
    command:
      - /bin/sh
      - -c
      - |
        ulimit -n 120000
        peggo orchestrator
    depends_on:
      injective:
        condition: service_healthy