services:
  peggo:
    build:
      context: ./cosmovisor
      dockerfile: Dockerfile.binary
      args:
        - DAEMON_VERSION=${DAEMON_VERSION}
        - BINARY_TAG=${BINARY_TAG}
        - USER=injective
        - DOWNLOAD_BASE_URL=${DOWNLOAD_BASE_URL:-}
    image: injective:local
    pull_policy: never
    user: injective
    environment:
      - DAEMON_VERSION=${DAEMON_VERSION}
      - EXTRA_FLAGS=${EXTRA_FLAGS:-}
      - NETWORK=${NETWORK:?NETWORK must be set}
      - PEGGO_ENV=${PEGGO_ENV:-prod}
      - PEGGO_LOG_LEVEL=${PEGGO_LOG_LEVEL:-info}
      - PEGGO_SERVICE_WAIT_TIMEOUT=${PEGGO_SERVICE_WAIT_TIMEOUT:-1m}
      - PEGGO_COSMOS_CHAIN_ID=${PEGGO_COSMOS_CHAIN_ID:-injective-1}
      - PEGGO_COSMOS_GRPC=${PEGGO_COSMOS_GRPC:-tcp://injective:9900}
      - PEGGO_TENDERMINT_RPC=${PEGGO_TENDERMINT_RPC:-http://injective:26657}
      - PEGGO_COSMOS_FEE_DENOM=${PEGGO_COSMOS_FEE_DENOM:-inj}
      - PEGGO_COSMOS_GAS_PRICES=${PEGGO_COSMOS_GAS_PRICES:-160000000inj}
      - PEGGO_COSMOS_KEYRING=${PEGGO_COSMOS_KEYRING:-file}
      - PEGGO_COSMOS_KEYRING_DIR=${PEGGO_COSMOS_KEYRING_DIR:-/cosmos/keyring-file}
      - PEGGO_COSMOS_KEYRING_APP=${PEGGO_COSMOS_KEYRING_APP:-}
      - PEGGO_COSMOS_FROM=${PEGGO_COSMOS_FROM:?PEGGO_COSMOS_FROM must be set to a valid address}
      - PEGGO_COSMOS_FROM_PASSPHRASE=${PEGGO_COSMOS_FROM_PASSPHRASE:-}
      - PEGGO_COSMOS_USE_LEDGER=${PEGGO_COSMOS_USE_LEDGER:-false}
      - PEGGO_ETH_CHAIN_ID=${PEGGO_ETH_CHAIN_ID:-1}
      - PEGGO_ETH_RPC=${PEGGO_ETH_RPC:-https://ethereum-rpc.publicnode.com}
      - PEGGO_ETH_KEYSTORE_DIR=${PEGGO_ETH_KEYSTORE_DIR:-/cosmos/config/peggo/keystore}
      - PEGGO_ETH_FROM=${PEGGO_ETH_FROM:?PEGGO_ETH_FROM must be set to a valid Ethereum address}
      - PEGGO_ETH_PASSPHRASE=${PEGGO_ETH_PASSPHRASE:-}
      - PEGGO_ETH_USE_LEDGER=${PEGGO_ETH_USE_LEDGER:-false}
      - PEGGO_ETH_GAS_PRICE_ADJUSTMENT=${PEGGO_ETH_GAS_PRICE_ADJUSTMENT:-1.3}
      - PEGGO_COINGECKO_API=${PEGGO_COINGECKO_API:-https://api.coingecko.com/api/v3}
      - PEGGO_RELAY_VALSETS=${PEGGO_RELAY_VALSETS:-true}
      - PEGGO_RELAY_BATCHES=${PEGGO_RELAY_BATCHES:-false}
      - PEGGO_MIN_BATCH_FEE_USD=${PEGGO_MIN_BATCH_FEE_USD:-0}
      - PEGGO_STATSD_PREFIX=${PEGGO_STATSD_PREFIX:-peggo.}
      - PEGGO_STATSD_ADDR=${PEGGO_STATSD_ADDR:-0.0.0.0:8125}
      - PEGGO_STATSD_STUCK_DUR=${PEGGO_STATSD_STUCK_DUR:-5m}
      - PEGGO_STATSD_MOCKING=${PEGGO_STATSD_MOCKING:-false}
      - PEGGO_STATSD_DISABLED=${PEGGO_STATSD_DISABLED:-false}
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - consensus-data:/cosmos
      - ./keys/operator:/cosmos/keyring-file:rw
      - type: bind
        source: ${PWD}/keys/ethereum-peggo/keystore.json
        target: /cosmos/config/peggo/keystore/keystore.json
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        peggo orchestrator
    depends_on:
      injective:
        condition: service_healthy
